CREATE DATABASE IF NOT EXISTS to_doxls
  CHARACTER SET UTF8;

CREATE TABLE items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  status TINYINT DEFAULT 0 NOT NULL,
  priority TINYINT DEFAULT 0 NOT NULL
);

CREATE TABLE tags (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  color VARCHAR(255) NOT NULL
);

CREATE TABLE items_tags (
  item_id INT,
  tag_id INT,
  PRIMARY KEY (item_id, tag_id),
  FOREIGN KEY (item_id)
    REFERENCES items(id)
    ON DELETE CASCADE,
  FOREIGN KEY (tag_id)
    REFERENCES tags(id)
    ON DELETE CASCADE 
);
